### PR TITLE
Autoland plugin (feature/land-overlay)

### PR DESCRIPTION
**Pull request by marcusfrolich**
This plugin was part of the NTNU Master Thesis "Automatic Ship Landing System for Fixed-Wing UAV" by Marcus Frølich. It issues an IMC command to DUNE for excecution of autoland.

### CODE REVIEW

**Comment by paulosousadias** [comment]
Thank for the contribution. I'll have a look at it.

**Comment by paulosousadias** [comment]
This will be merged but I guess that there is some commits missing for DUNE on the plan generator?
Some improvements can be made. We don't see what the vehicle is going to do, except for when the plan comes back from the vehicle.
Probably some improvements on the parameters settings can be made.

**Comment by marcusfrolich** [comment]
Hi,

I'm not sure if the needed SW (like custom made path planner) on the DUNE
side is committed properly, but it worked when I used it. I believe there
are new people working on it at NTNU now, and I won't be doing any more
work on it myself. The pull request is to make it easier for further
development by other master/PhD students.

Marcus

tir. 22. des. 2015 kl. 12.52 skrev Paulo Dias <notifications@github.com>:

**Comment by paulosousadias** [comment]
Hi Marcus,

 Thanks for the reply. I will try through João Fortuna to get the status on this.

Paulo

**Pull request merged**
