### PR TITLE
Cleaned up leftover files and unused classes.

### PR DESCRIPTION
**Pull request by rasmartins**

### CODE REVIEW

**Comment by rasmartins** [comment]
Any comments about this pull request ? I have a few more cleanups pending.

**Comment by paulosousadias** [comment]
Did not had time to look at it properly. I'll have a look over the weekend.

**Comment by zepinto** [comment]
keep it up :)

**Comment by rasmartins** [comment]
Oh, but I will ;)

**Comment by rasmartins** [comment]
Can someone update me on the status of this pull request ?

**Comment by zepinto** [comment]
Paulo Dias asked to be responsible for this pull request.

**Comment by rasmartins** [comment]
Just a heads up, I'm going to merge this in a few hours.

**Pull request merged**
