### PR TITLE
Removed obsolete fields from LBL Beacons configuration files. Added benthos1 and benthos6

### PR DESCRIPTION
**Pull request by rasmartins**

### CODE REVIEW

**Comment by paulosousadias** [comment]
Still not ready for merge. I still need to cleanup some errors.

**Comment by rasmartins** [comment]
What kind of errors ? I can clean them.

**Comment by paulosousadias** [comment]
When sending the beacons a null pointer is trigger. Did you miss a push?

**Comment by zepinto** [comment]
It was fixed and it is now merged with develop.

**Pull request merged**
